import sys

#1 Counting DNA nucleotides
"""
sequence = "TGCGATCTTGGCACGGTAGTATCGAGATGCATGCCGTCGTACGCCGCGCTGACCACAAACCCTCTCCCAGGGAGTGTCAATCTATAGTAGCCCAGTGCGCGGGTACGGCTGGAATGAGGCTCCTCAGTTTATTAGACACAGCGTCGATTTGACATGCACATGCGGGTAGGTGTTAACCCCAATGAAACACGTTGGTCCGTGAGAGGTTCAACCGCCTAGCCTACGATAGGGACCGACAGAGGACGAGGACAGTCTGTTACTATTCCAATGGTGTAGGCCCGACTTAATCAGAGACCAGCAGATCATAGCGCTGATAAGTCAGATATCTTTTGCACCTCAGAATGAACGCTTAGTACCAACATGCGGGTTCTAGAACAACCGAACTAACGTAGGAGAACAGTAGGCTCCTTCGCGTGCGATACGCTCTTGAAGTGTTTAAATGATACTTTTTCAACTGGTACCGGGGGCCAGCTAAGAATGGGATTCCAGGGAGGTCTCCAGTCCTTTATTCGTTCGGGTTGCTCATAACACATCTTCTGCGCCCCCCCAAAGATGTATCGTCGGTTCCGTAATAGCATCCCGATGTAATTGACGCGGACCTCCGGGTACAGGTGCAACGTATGGCTGGTCTCTCACAACACATTTCGAATACAAACGGTCAGGAGATAGGGGCAAAGAAGCGGCGAATCAACCAGTCCTATGCCTTCATGCTCATTTAGATGATGGAGTTACACTAAAGATCAGCGCATCCGCCTCGTTGCCTCATGTAGATCCTACCGATTTACAACTCCGGGTACCGGATATGACTAATGATGGTGGTCCCGCTGCTGGGACTTGGAACGACCGTGGATACCGGGATTCCCATCTT"
print(sequence.count("A"))
print(sequence.count("C"))
print(sequence.count("G"))
print(sequence.count("T"))
"""

#2 Counting DNA nucleotides
"""
print(*map(input().count, "ACGT"))
"""

#3 Counting DNA nucleotides
"""
data = open("rosalind_dna.txt", "r")
sequence = data.read()
print("{} {} {} {}".format(sequence.count("A"), sequence.count("C"), sequence.count("G"), sequence.count("T")))
"""

#4 Counting DNA nucleotides
"""
sequence = sys.argv[1]
print("{} {} {} {}".format(sequence.count("A"), sequence.count("C"), sequence.count("G"), sequence.count("T")))
"""
